# Generated by Django 4.2.5 on 2023-09-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='creation_data',
            new_name='creation_date',
        ),
    ]
