# Generated by Django 4.2.5 on 2023-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_creation_data_record_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='provinence',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
