# Generated by Django 4.2.5 on 2023-09-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_provinence_record_province_alter_record_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='province',
            new_name='provinence',
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=225),
        ),
    ]
